# Generated by Django 5.0.2 on 2024-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albumsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.TextField()),
                ('bgColor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='songsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='songs/')),
                ('desc', models.TextField()),
                ('duration', models.CharField(max_length=5)),
            ],
        ),
    ]
